#!/bin/bash
# 简单的手动初始化指南

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "PostgreSQL 数据库手动初始化指南"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "请按照以下步骤手动执行："
echo ""
echo "1️⃣  连接到 PostgreSQL"
echo "   psql postgres"
echo ""
echo "2️⃣  创建用户（在 psql 中执行）"
echo "   CREATE USER ruo WITH PASSWORD '123456';"
echo ""
echo "3️⃣  创建数据库（在 psql 中执行）"
echo "   CREATE DATABASE ruo OWNER ruo;"
echo ""
echo "4️⃣  授予权限（在 psql 中执行）"
echo "   GRANT ALL PRIVILEGES ON DATABASE ruo TO ruo;"
echo ""
echo "5️⃣  退出 psql"
echo "   \\q"
echo ""
echo "6️⃣  连接到 ruo 数据库并授予 schema 权限"
echo "   psql -U ruo -d ruo"
echo "   GRANT ALL ON SCHEMA public TO ruo;"
echo "   \\q"
echo ""
echo "7️⃣  验证连接"
echo "   PGPASSWORD=123456 psql -U ruo -d ruo -c 'SELECT version();'"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "💡 提示："
echo "   - 如果提示权限不足，请使用 sudo -u postgres psql"
echo "   - macOS Homebrew 安装的 PostgreSQL 通常可以直接使用当前用户"
echo ""
