-- Add new columns to stocks table
ALTER TABLE stocks ADD COLUMN IF NOT EXISTS current_price FLOAT;
ALTER TABLE stocks ADD COLUMN IF NOT EXISTS change_pct FLOAT;
ALTER TABLE stocks ADD COLUMN IF NOT EXISTS volume FLOAT;
ALTER TABLE stocks ADD COLUMN IF NOT EXISTS amount FLOAT;
ALTER TABLE stocks ADD COLUMN IF NOT EXISTS turnover_rate FLOAT;
ALTER TABLE stocks ADD COLUMN IF NOT EXISTS pe_dynamic FLOAT;
ALTER TABLE stocks ADD COLUMN IF NOT EXISTS pb FLOAT;
ALTER TABLE stocks ADD COLUMN IF NOT EXISTS total_market_cap FLOAT;
ALTER TABLE stocks ADD COLUMN IF NOT EXISTS circulating_market_cap FLOAT;
